// <auto-generated />
namespace IAAITW.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class adjustfeildintablememberAccount : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(adjustfeildintablememberAccount));
        
        string IMigrationMetadata.Id
        {
            get { return "202511130704232_adjust feild in table memberAccount"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
