// <auto-generated />
namespace IAAITW.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class addnewstable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addnewstable));
        
        string IMigrationMetadata.Id
        {
            get { return "202511140613595_add news table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
