// <auto-generated />
namespace IAAITW.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class adjustfeildincontacttable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(adjustfeildincontacttable));
        
        string IMigrationMetadata.Id
        {
            get { return "202512080721114_adjust feild in contact table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
