// <auto-generated />
namespace IAAITW.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class addfeildupdateduseridinalltable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addfeildupdateduseridinalltable));
        
        string IMigrationMetadata.Id
        {
            get { return "202511040730514_add feild updateduserid in all table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
